class HomeController < ApplicationController
  def index
  end

  def fetch_meals
    api = 'https://www.eatthismuch.com/weeklyplanner/regenerate-day-json/'
    response = HTTParty.post(api, body: body.to_json)
    @meals = []
    response["result_list"].each do |list|
      begin 
        list[0]["diet"]["meals"].each do |meal|
          @meals << meal["foods"].map { |food| 
            food_obj = response["food_info_objects"].find { |info| info["id"] == food["food_id"] }
            { 
              img:  food_obj["default_image"]["image"],
              name: food_obj["food_name"],
              fats: food_obj["fats"].round(3),
              fiber: food_obj["fiber"].round(3),
              cholesterol: food_obj["cholesterol"].round(3),
              calories: food_obj["calories"].round(3),
              carbs: food_obj["carbs"].round(3)
            }
          }
        end
        break
      rescue 
      end
    end
  end

  private 
    def body
      {
         "day_json":{
            "user_settings":{
               "activity_level":"1.2",
               "algorithm":1,
               "age":nil,
               "bodyfat":nil,
               "beta_user":true,
               "todays_weight":nil,
               "use_weight_goal":false,
               "use_net_carbs":false,
               "weight_goal":nil,
               "weight_goal_weekly_rate":nil,
               "custom_exclusions":"",
               "daily_price_limit":0,
               "exclusions":"",
               "friend_signups":0,
               "friend_successes":0,
               "gender":nil,
               "goal":nil,
               "hide_gender":true,
               "limit_price":false,
               "link_clicks":0,
               "months_saved_up":0,
               "number_curated_recipes":0,
               "preset_diet":"anything",
               "total_months_earned":0,
               "units":"I",
               "use_leftovers":false,
               "complexity_level":1,
               "generator_focus":0,
               "show_walkthrough_prompt":true,
               "single_template_diet":true,
               "timezone":"5.5",
               "shopping_day":5,
               "use_partial_servings":false,
               "resource_uri":-436527263
            },
            "meal_plan_dates":[
               {
                  "date":nil,
                  "diet":{
                     "resource_uri":-167616315,
                     "num_meals": params[:meal_count] || 4,
                     "nutrition_profile":{
                        "calories": params[:cal_amt] || 2000,
                        "cholesterol":300,
                        "date_made":nil,
                        "deleted":false,
                        "description":nil,
                        "fiber":25,
                        "macro_scheme":"grams",
                        "max_carbs":150,
                        "max_fats":156,
                        "max_proteins":175,
                        "min_carbs":50,
                        "min_fats":44,
                        "min_proteins":50,
                        "percent_carbs":40,
                        "percent_fats":30,
                        "percent_proteins":30,
                        "sodium":2400,
                        "title":"My Nutrition Targets",
                        "watch_cholesterol":false,
                        "watch_sodium":false,
                        "resource_uri":-446204592
                     },
                     "meals":[
                        {
                           "resource_uri":-244240850,
                           "meal_number":0,
                           "foods":[
                              {
                                 "id":-782571963,
                                 "food_id":386743,
                                 "amount":1,
                                 "units":1,
                                 "is_leftovers":false,
                                 "leftovers_from":nil,
                                 "leftovers_from_id":nil,
                                 "eaten":false,
                                 "user_chosen":false,
                                 "scaled_amount":nil,
                                 "has_leftovers":false,
                                 "resource_uri":"-782571963",
                                 "makes_leftovers_for":nil,
                                 "uses_leftovers_from":nil
                              }
                           ],
                           "meal_type":{
                              "title":"Breakfast",
                              "size_slider":100,
                              "family_scale":1,
                              "breakfast":2,
                              "takeout":false,
                              "min_preptime":0,
                              "max_preptime":30,
                              "min_cooktime":0,
                              "max_cooktime":30,
                              "max_totaltime":30,
                              "complexity":2,
                              "override_complexity":false,
                              "only_use_recurring":false,
                              "deleted":false,
                              "resource_uri":-750279847
                           },
                           "id":-244240850
                        },
                        {
                           "resource_uri":-89885469,
                           "meal_number":1,
                           "foods":[
                              {
                                 "id":-857076727,
                                 "food_id":33519,
                                 "amount":1,
                                 "units":1,
                                 "is_leftovers":false,
                                 "leftovers_from":nil,
                                 "leftovers_from_id":nil,
                                 "eaten":false,
                                 "user_chosen":false,
                                 "scaled_amount":nil,
                                 "has_leftovers":false,
                                 "resource_uri":"-857076727",
                                 "makes_leftovers_for":nil,
                                 "uses_leftovers_from":nil
                              },
                              {
                                 "id":-962306435,
                                 "food_id":474253,
                                 "amount":1,
                                 "units":1,
                                 "is_leftovers":false,
                                 "leftovers_from":nil,
                                 "leftovers_from_id":nil,
                                 "eaten":false,
                                 "user_chosen":false,
                                 "scaled_amount":nil,
                                 "has_leftovers":false,
                                 "resource_uri":"-962306435",
                                 "makes_leftovers_for":nil,
                                 "uses_leftovers_from":nil
                              }
                           ],
                           "meal_type":{
                              "title":"Lunch",
                              "size_slider":100,
                              "family_scale":1,
                              "breakfast":0,
                              "takeout":false,
                              "min_preptime":0,
                              "max_preptime":30,
                              "min_cooktime":0,
                              "max_cooktime":0,
                              "max_totaltime":30,
                              "complexity":2,
                              "override_complexity":false,
                              "only_use_recurring":false,
                              "deleted":false,
                              "resource_uri":-632269272
                           },
                           "id":-89885469
                        },
                        {
                           "resource_uri":-674394550,
                           "meal_number":2,
                           "foods":[
                              {
                                 "id":-912570568,
                                 "food_id":36663,
                                 "amount":1,
                                 "units":1,
                                 "is_leftovers":false,
                                 "leftovers_from":nil,
                                 "leftovers_from_id":nil,
                                 "eaten":false,
                                 "user_chosen":false,
                                 "scaled_amount":nil,
                                 "has_leftovers":false,
                                 "resource_uri":"-912570568",
                                 "makes_leftovers_for":nil,
                                 "uses_leftovers_from":nil
                              },
                              {
                                 "id":-23543727,
                                 "food_id":412930,
                                 "amount":2,
                                 "units":1,
                                 "is_leftovers":false,
                                 "leftovers_from":nil,
                                 "leftovers_from_id":nil,
                                 "eaten":false,
                                 "user_chosen":false,
                                 "scaled_amount":nil,
                                 "has_leftovers":false,
                                 "resource_uri":"-23543727",
                                 "makes_leftovers_for":nil,
                                 "uses_leftovers_from":nil
                              }
                           ],
                           "meal_type":{
                              "title":"Dinner",
                              "size_slider":125,
                              "family_scale":1,
                              "breakfast":0,
                              "takeout":false,
                              "min_preptime":0,
                              "max_preptime":30,
                              "min_cooktime":1,
                              "max_cooktime":30,
                              "max_totaltime":30,
                              "complexity":2,
                              "override_complexity":false,
                              "only_use_recurring":false,
                              "deleted":false,
                              "resource_uri":-358280328
                           },
                           "id":-674394550
                        },
                        {
                           "resource_uri":-46112857,
                           "meal_number":3,
                           "foods":[
                              {
                                 "id":-980728952,
                                 "food_id":473713,
                                 "amount":1,
                                 "units":1,
                                 "is_leftovers":false,
                                 "leftovers_from":nil,
                                 "leftovers_from_id":nil,
                                 "eaten":false,
                                 "user_chosen":false,
                                 "scaled_amount":nil,
                                 "has_leftovers":false,
                                 "resource_uri":"-980728952",
                                 "makes_leftovers_for":nil,
                                 "uses_leftovers_from":nil
                              },
                              {
                                 "id":-254874549,
                                 "food_id":524950,
                                 "amount":1,
                                 "units":1,
                                 "is_leftovers":false,
                                 "leftovers_from":nil,
                                 "leftovers_from_id":nil,
                                 "eaten":false,
                                 "user_chosen":false,
                                 "scaled_amount":nil,
                                 "has_leftovers":false,
                                 "resource_uri":"-254874549",
                                 "makes_leftovers_for":nil,
                                 "uses_leftovers_from":nil
                              }
                           ],
                           "meal_type":{
                              "title":"Snack",
                              "size_slider":50,
                              "family_scale":1,
                              "breakfast":1,
                              "takeout":false,
                              "min_preptime":0,
                              "max_preptime":30,
                              "min_cooktime":0,
                              "max_cooktime":0,
                              "max_totaltime":15,
                              "complexity":1,
                              "override_complexity":false,
                              "only_use_recurring":false,
                              "deleted":false,
                              "resource_uri":-220227331
                           },
                           "id":-46112857
                        }
                     ]
                  }
               }
            ],
            "is_day_regenerate":true
         },
         "existing_food_ids":[
            386743,
            33519,
            474253,
            36663,
            412930,
            473713,
            524950
         ],
         "use_meal_pools":true
}
    end
end
